#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ActorLayerUtilities

#include "Basic.hpp"


namespace SDK
{

// ScriptStruct ActorLayerUtilities.ActorLayer
// 0x0008 (0x0008 - 0x0000)
struct FActorLayer final
{
public:
	class FName                                   Name;                                              // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FActorLayer) == 0x000004, "Wrong alignment on FActorLayer");
static_assert(sizeof(FActorLayer) == 0x000008, "Wrong size on FActorLayer");
static_assert(offsetof(FActorLayer, Name) == 0x000000, "Member 'FActorLayer::Name' has a wrong offset!");

}

