#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UI_OP_Check

#include "Basic.hpp"

#include "BP_UI_OP_Check_classes.hpp"
#include "BP_UI_OP_Check_parameters.hpp"


namespace SDK
{

// Function BP_UI_OP_Check.BP_UI_OP_Check_C.OnChildCheckStateChangedEDisp__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void UBP_UI_OP_Check_C::OnChildCheckStateChangedEDisp__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UI_OP_Check_C", "OnChildCheckStateChangedEDisp__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UI_OP_Check.BP_UI_OP_Check_C.OnChildCheckStateChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsChecked                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_UI_OP_Check_C::OnChildCheckStateChanged(bool bIsChecked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UI_OP_Check_C", "OnChildCheckStateChanged");

	Params::BP_UI_OP_Check_C_OnChildCheckStateChanged Parms{};

	Parms.bIsChecked = bIsChecked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UI_OP_Check.BP_UI_OP_Check_C.ExecuteUbergraph_BP_UI_OP_Check
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_UI_OP_Check_C::ExecuteUbergraph_BP_UI_OP_Check(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UI_OP_Check_C", "ExecuteUbergraph_BP_UI_OP_Check");

	Params::BP_UI_OP_Check_C_ExecuteUbergraph_BP_UI_OP_Check Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UI_OP_Check.BP_UI_OP_Check_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_UI_OP_Check_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UI_OP_Check_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

