#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DynamicSDFGenerator

#include "Basic.hpp"

#include "b1MinusManaged_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DynamicSDFGenerator.DynamicSDFGenerator_C
// 0x0000 (0x02F8 - 0x02F8)
class ADynamicSDFGenerator_C final : public ABGUDynamicSDFGenerator
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DynamicSDFGenerator_C">();
	}
	static class ADynamicSDFGenerator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADynamicSDFGenerator_C>();
	}
};
static_assert(alignof(ADynamicSDFGenerator_C) == 0x000008, "Wrong alignment on ADynamicSDFGenerator_C");
static_assert(sizeof(ADynamicSDFGenerator_C) == 0x0002F8, "Wrong size on ADynamicSDFGenerator_C");

}

