#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EQG_simpleteleport_donut

#include "Basic.hpp"

#include "b1_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass EQG_simpleteleport_donut.EQG_simpleteleport_donut_C
// 0x0000 (0x00F0 - 0x00F0)
class UEQG_simpleteleport_donut_C final : public UGSEQG_Donut
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EQG_simpleteleport_donut_C">();
	}
	static class UEQG_simpleteleport_donut_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEQG_simpleteleport_donut_C>();
	}
};
static_assert(alignof(UEQG_simpleteleport_donut_C) == 0x000008, "Wrong alignment on UEQG_simpleteleport_donut_C");
static_assert(sizeof(UEQG_simpleteleport_donut_C) == 0x0000F0, "Wrong size on UEQG_simpleteleport_donut_C");

}

