#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GSFileHelper

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class GSFileHelper.GSFileHelper
// 0x0000 (0x0028 - 0x0028)
class UGSFileHelper final : public UBlueprintFunctionLibrary
{
public:
	static bool CreateDirectory(const class FString& Directory);
	static bool DeleteDirectory(const class FString& Directory);
	static bool DeleteFile(const class FString& Filename);
	static bool DirectoryExists(const class FString& Directory);
	static bool FileExists(const class FString& Filename);
	static int64 FileSize(const class FString& Filename);
	static void FindFiles(const class FString& Directory, TArray<class FString>* FoundFiles, const class FString& FileExtension);
	static void FindFilesRecursively(const class FString& Directory, TArray<class FString>* FoundFiles, const class FString& FileExtension);
	static int64 GetTimeStampTicks(const class FString& Filename);
	static bool ReadFile(const class FString& Filename, TArray<uint8>* BytesToRead, bool IsStandardPath);
	static bool WriteFile(const class FString& Filename, const TArray<uint8>& BytesToWrite, bool bAppend, bool IsStandardPath);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"GSFileHelper">();
	}
	static class UGSFileHelper* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGSFileHelper>();
	}
};
static_assert(alignof(UGSFileHelper) == 0x000008, "Wrong alignment on UGSFileHelper");
static_assert(sizeof(UGSFileHelper) == 0x000028, "Wrong size on UGSFileHelper");

}

