#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MediaPlayerTest_UMG

#include "Basic.hpp"

#include "MediaPlayerTest_UMG_classes.hpp"
#include "MediaPlayerTest_UMG_parameters.hpp"


namespace SDK
{

// Function MediaPlayerTest_UMG.MediaPlayerTest_UMG_C.ExecuteUbergraph_MediaPlayerTest_UMG
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMediaPlayerTest_UMG_C::ExecuteUbergraph_MediaPlayerTest_UMG(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MediaPlayerTest_UMG_C", "ExecuteUbergraph_MediaPlayerTest_UMG");

	Params::MediaPlayerTest_UMG_C_ExecuteUbergraph_MediaPlayerTest_UMG Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MediaPlayerTest_UMG.MediaPlayerTest_UMG_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UMediaPlayerTest_UMG_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MediaPlayerTest_UMG_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MediaPlayerTest_UMG.MediaPlayerTest_UMG_C.BndEvt__MediaPlayerTest_UMG_PlayButtonMp4_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMediaPlayerTest_UMG_C::BndEvt__MediaPlayerTest_UMG_PlayButtonMp4_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MediaPlayerTest_UMG_C", "BndEvt__MediaPlayerTest_UMG_PlayButtonMp4_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MediaPlayerTest_UMG.MediaPlayerTest_UMG_C.BndEvt__MediaPlayerTest_UMG_PlayButtonClose_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMediaPlayerTest_UMG_C::BndEvt__MediaPlayerTest_UMG_PlayButtonClose_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MediaPlayerTest_UMG_C", "BndEvt__MediaPlayerTest_UMG_PlayButtonClose_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MediaPlayerTest_UMG.MediaPlayerTest_UMG_C.BndEvt__MediaPlayerTest_UMG_PlayButtonBk2_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMediaPlayerTest_UMG_C::BndEvt__MediaPlayerTest_UMG_PlayButtonBk2_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MediaPlayerTest_UMG_C", "BndEvt__MediaPlayerTest_UMG_PlayButtonBk2_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}

}

